"""
Multi-Agent Debate & Consensus Verification — Expert critique system.

Orchestrates sequential and parallel debates between four specialized reviewer agents
(Security, Performance, Correctness, and Style) to build consensus on code quality.

Also provides an **Agent Council** for strategic decision-making: convenes a panel
of expert personas, collects opinions, runs iterative debate rounds, and produces
a final vote with consensus summary.
"""

from __future__ import annotations

import json
import logging
import re
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field

from nexus_agent.llm.base import LLMProvider, Message, Role

logger = logging.getLogger(__name__)


@dataclass
class ReviewerPersona:
    """Represents a specialized reviewer persona in the debate engine."""
    name: str
    focus_area: str
    system_prompt: str


@dataclass
class CritiqueFeedback:
    """Critique details from a specific reviewer."""
    reviewer_name: str
    score: int  # 0 to 100
    approved: bool
    issues: list[str] = field(default_factory=list)
    suggestions: list[str] = field(default_factory=list)
    comments: str = ""


@dataclass
class DebateVerdict:
    """Consensus verdict generated by the Judge agent after reviews."""
    consensus_score: int                   # 0 to 100 aggregated score
    final_approved: bool                   # True if consensus is achieved
    reviewer_scores: dict[str, int]        # Individual scores
    aggregated_issues: list[str]          # Union of critical/major issues
    consensus_summary: str                 # Markdown summary of consensus details
    recommendations: list[str]             # List of actionable refactoring items
    rounds_conducted: int = 1
    reworked_code: str | None = None


# --------------------------------------------------------------------------- #
#  Reviewer Persona Prompts                                                   #
# --------------------------------------------------------------------------- #

SECURITY_AUDITOR = ReviewerPersona(
    name="SecurityAuditor",
    focus_area="security",
    system_prompt=(
        "You are an expert Cyber Security Auditor and penetration tester.\n"
        "Your task is to review the proposed code changes and identify potential security risks:\n"
        "- Injection vulnerabilities (SQLi, command injection, XSS)\n"
        "- Secrets, credentials, or API keys hardcoded in source\n"
        "- Unsafe libraries, insecure deserialization, open permissions\n"
        "- Missing access controls or authentication flaws\n\n"
        "Be extremely paranoid and rigorous. You MUST reply with a valid JSON containing:\n"
        "{\n"
        "  \"score\": <int 0-100>,\n"
        "  \"approved\": <bool>,\n"
        "  \"issues\": [\"critical/major issues found\"],\n"
        "  \"suggestions\": [\"ideas to mitigate issues\"],\n"
        "  \"comments\": \"overall feedback\"\n"
        "}"
    )
)

PERFORMANCE_ENGINEER = ReviewerPersona(
    name="PerformanceEngineer",
    focus_area="performance",
    system_prompt=(
        "You are an expert Performance and Reliability Engineer.\n"
        "Your task is to analyze proposed code changes for execution bottlenecks and resource usage:\n"
        "- Inefficient loops, O(N^2) algorithms, unnecessary DB/network queries\n"
        "- Resource leaks (unclosed sockets, unclosed files, DB connections)\n"
        "- Memory overhead, caching possibilities, blocking I/O inside async functions\n"
        "- Thread safety issues or concurrency bottlenecks\n\n"
        "Be strict and highly mathematical. You MUST reply with a valid JSON containing:\n"
        "{\n"
        "  \"score\": <int 0-100>,\n"
        "  \"approved\": <bool>,\n"
        "  \"issues\": [\"bottlenecks found\"],\n"
        "  \"suggestions\": [\"performance improvements\"],\n"
        "  \"comments\": \"overall feedback\"\n"
        "}"
    )
)

CORRECTNESS_QA = ReviewerPersona(
    name="CorrectnessQA",
    focus_area="correctness",
    system_prompt=(
        "You are a strict QA Automation Engineer and Software Architect.\n"
        "Your task is to review proposed code changes for logic bugs and compliance:\n"
        "- Off-by-one errors, edge cases, incorrect conditional logic\n"
        "- Type safety, type conversion errors, unhandled exception/error cases\n"
        "- Compliance with user requirements and existing codebase patterns\n"
        "- Missing validation or boundary checks\n\n"
        "Be exact, literal, and detailed. You MUST reply with a valid JSON containing:\n"
        "{\n"
        "  \"score\": <int 0-100>,\n"
        "  \"approved\": <bool>,\n"
        "  \"issues\": [\"correctness bugs found\"],\n"
        "  \"suggestions\": [\"corrections\"],\n"
        "  \"comments\": \"overall feedback\"\n"
        "}"
    )
)

STYLE_LINTER = ReviewerPersona(
    name="StyleLinter",
    focus_area="style",
    system_prompt=(
        "You are an expert Software Maintainability & Style Critic.\n"
        "Your task is to evaluate the code changes against clean code conventions (PEP 8, idiomatic structure):\n"
        "- Readability, naming conventions, docstrings, variable scoping\n"
        "- Complex code blocks that need refactoring or simplifications\n"
        "- Code duplication or adherence to SOLID principles\n"
        "- Formatting, redundant imports, unused code\n\n"
        "Focus on long-term project health. You MUST reply with a valid JSON containing:\n"
        "{\n"
        "  \"score\": <int 0-100>,\n"
        "  \"approved\": <bool>,\n"
        "  \"issues\": [\"style/maintainability issues\"],\n"
        "  \"suggestions\": [\"clean code styling suggestions\"],\n"
        "  \"comments\": \"overall feedback\"\n"
        "}"
    )
)


class DebateEngine:
    """Manages multi-agent debate and consensus loops."""

    def __init__(self, provider: LLMProvider | None = None, approval_threshold: int = 70):
        """Initialize the debate engine.

        Args:
            provider: LLM provider instance.
            approval_threshold: Combined score threshold for passing.
        """
        self.provider = provider
        self.approval_threshold = approval_threshold
        self.personas = [
            SECURITY_AUDITOR,
            PERFORMANCE_ENGINEER,
            CORRECTNESS_QA,
            STYLE_LINTER
        ]

    def _review_single(self, persona: ReviewerPersona, code_changes: str, context: str) -> CritiqueFeedback:
        """Run a single reviewer and return CritiqueFeedback."""
        try:
            system_prompt = persona.system_prompt
            user_prompt = (
                f"Please review the proposed code changes below.\n"
                f"## Code Changes:\n{code_changes}\n\n"
                f"## Additional Context:\n{context}\n\n"
                f"Respond with the requested JSON review object."
            )

            messages = [
                Message(role=Role.SYSTEM, content=system_prompt),
                Message(role=Role.USER, content=user_prompt),
            ]

            response = self.provider.chat_completion(
                messages=messages,
                temperature=0.1,
                max_tokens=1500
            )

            content = (response.content or "").strip()
            if "```" in content:
                match = re.search(r"```(?:json)?\s*\n?(.*?)\n?```", content, re.DOTALL)
                if match:
                    content = match.group(1).strip()

            start = content.find("{")
            end = content.rfind("}") + 1
            if start >= 0 and end > start:
                data = json.loads(content[start:end])
            else:
                data = json.loads(content)

            return CritiqueFeedback(
                reviewer_name=persona.name,
                score=max(0, min(100, int(data.get("score", 70)))),
                approved=bool(data.get("approved", True)),
                issues=data.get("issues", []),
                suggestions=data.get("suggestions", []),
                comments=data.get("comments", "")
            )

        except (ValueError, RuntimeError) as e:
            logger.warning(f"Reviewer '{persona.name}' failed: {e}. Generating default review.", exc_info=True)
            return CritiqueFeedback(
                reviewer_name=persona.name,
                score=50,
                approved=False,
                comments=f"Reviewer failed: {e}"
            )

    def review_changes(self, code_changes: str, context: str = "") -> list[CritiqueFeedback]:
        """Trigger parallel expert reviews from all 4 personas using ThreadPoolExecutor."""
        feedbacks: list[CritiqueFeedback] = []

        if not self.provider:
            return self._heuristic_review(code_changes)

        with ThreadPoolExecutor(max_workers=len(self.personas)) as executor:
            futures = {
                executor.submit(self._review_single, persona, code_changes, context): persona
                for persona in self.personas
            }
            for future in as_completed(futures):
                try:
                    feedbacks.append(future.result())
                except (ValueError, RuntimeError, OSError) as e:
                    persona = futures[future]
                    logger.error(f"Reviewer '{persona.name}' thread failed: {e}", exc_info=True)
                    feedbacks.append(CritiqueFeedback(
                        reviewer_name=persona.name,
                        score=50,
                        approved=False,
                        comments=f"Reviewer thread failed: {e}"
                    ))

        return feedbacks

    def _heuristic_review(self, code_changes: str) -> list[CritiqueFeedback]:
        """Simple rule-based review engine in the absence of an LLM."""
        feedbacks = []
        lower_code = code_changes.lower()

        # 1. Security Review
        sec_issues = []
        sec_sug = []
        sec_score = 95
        if "eval(" in lower_code or "exec(" in lower_code:
            sec_issues.append("Unsafe dynamic execution `eval` / `exec` used!")
            sec_sug.append("Refactor to use static mapping or safe AST evaluation.")
            sec_score -= 30
        if "password" in lower_code or "secret" in lower_code or "api_key" in lower_code:
            if re.search(r'(?:password|secret|api_key|token)\s*=\s*[\'"][^\'"]+[\'"]', lower_code):
                sec_issues.append("Potential hardcoded sensitive keys or credentials detected.")
                sec_sug.append("Store secrets in environment variables or configuration files.")
                sec_score -= 20
        feedbacks.append(CritiqueFeedback("SecurityAuditor", sec_score, sec_score >= 70, sec_issues, sec_sug, "Rule-based security scan completed."))

        # 2. Performance Review
        perf_issues = []
        perf_sug = []
        perf_score = 90
        if "time.sleep(" in lower_code:
            perf_issues.append("Synchronous `time.sleep` call block detected.")
            perf_sug.append("Use async sleep or schedule timers if executing in an async context.")
            perf_score -= 10
        if ".read()" in lower_code and "with open" in lower_code:
            perf_sug.append("Ensure reading chunks for extremely large files.")
        feedbacks.append(CritiqueFeedback("PerformanceEngineer", perf_score, perf_score >= 70, perf_issues, perf_sug, "Rule-based performance scan completed."))

        # 3. Correctness Review
        corr_issues = []
        corr_sug = []
        corr_score = 85
        if "except:" in lower_code or "except Exception:" in lower_code:
            if "raise" not in lower_code and "pass" in lower_code:
                corr_issues.append("Silent exception catching detected (except without raise or log).")
                corr_sug.append("At least log the error or specify a more targeted exception type.")
                corr_score -= 15
        feedbacks.append(CritiqueFeedback("CorrectnessQA", corr_score, corr_score >= 70, corr_issues, corr_sug, "Rule-based correctness scan completed."))

        # 4. Style Review
        style_issues = []
        style_sug = []
        style_score = 80
        if "todo" in lower_code or "fixme" in lower_code:
            style_sug.append("Resolve open TODOs and FIXMEs before finalizing implementation.")
        feedbacks.append(CritiqueFeedback("StyleLinter", style_score, style_score >= 70, style_issues, style_sug, "Rule-based style linter completed."))

        return feedbacks

    def judge(self, reviews: list[CritiqueFeedback], rounds: int = 1) -> DebateVerdict:
        """Judge agent role: aggregates reviewer scores, resolves issues, produces final verdict."""
        if not reviews:
            return DebateVerdict(100, True, {}, [], "No reviews to judge.", [])

        reviewer_scores = {r.reviewer_name: r.score for r in reviews}
        consensus_score = int(sum(r.score for r in reviews) / len(reviews))

        aggregated_issues = []
        recommendations = []

        for r in reviews:
            for issue in r.issues:
                aggregated_issues.append(f"[{r.reviewer_name}] {issue}")
            for sug in r.suggestions:
                recommendations.append(f"[{r.reviewer_name}] {sug}")

        final_approved = consensus_score >= self.approval_threshold and all(r.approved for r in reviews)

        summary_lines = [
            f"### ⚖️ Debate Verdict Summary (Consensus Score: {consensus_score}/100)",
            "",
            f"**Status:** {'🟢 APPROVED' if final_approved else '🔴 REJECTED / NEEDS REWORK'}",
            "",
            "#### Reviewer Scores:"
        ]
        for name, score in reviewer_scores.items():
            icon = "✅" if score >= self.approval_threshold else "⚠️"
            summary_lines.append(f"- {icon} **{name}:** {score}/100")

        consensus_summary = "\n".join(summary_lines)

        return DebateVerdict(
            consensus_score=consensus_score,
            final_approved=final_approved,
            reviewer_scores=reviewer_scores,
            aggregated_issues=aggregated_issues,
            consensus_summary=consensus_summary,
            recommendations=recommendations,
            rounds_conducted=rounds
        )

    def run_debate(self, code_changes: str, context: str = "", max_rounds: int = 2) -> DebateVerdict:
        """Run debate loop.

        Args:
            code_changes: The code changes / diff.
            context: Additional context or codebase info.
            max_rounds: Maximum revision rounds.

        Returns:
            The final DebateVerdict.
        """
        current_changes = code_changes
        verdict = None

        for r_num in range(1, max_rounds + 1):
            reviews = self.review_changes(current_changes, context)
            verdict = self.judge(reviews, rounds=r_num)

            if verdict.final_approved:
                logger.info(f"Consensus approved in round {r_num}!")
                break

            if r_num < max_rounds and self.provider:
                # LLM correction cycle: try to self-heal code changes using Judge recommendations
                logger.info(f"Consensus failed in round {r_num} with score {verdict.consensus_score}. Reworking code changes...")
                try:
                    system_prompt = (
                        "You are an expert senior code refactoring assistant. Your job is to address the issues raised "
                        "by multiple code reviewers and produce the perfect, fixed code changes block."
                    )
                    user_prompt = (
                        f"Proposed changes:\n{current_changes}\n\n"
                        f"Reviewer issues:\n" + "\n".join(f"- {i}" for i in verdict.aggregated_issues) + "\n\n"
                        "Refactoring recommendations:\n" + "\n".join(f"- {r}" for r in verdict.recommendations) + "\n\n"
                        "Please output only the complete, fixed code block."
                    )
                    messages = [
                        Message(role=Role.SYSTEM, content=system_prompt),
                        Message(role=Role.USER, content=user_prompt),
                    ]
                    response = self.provider.chat_completion(
                        messages=messages,
                        temperature=0.1,
                        max_tokens=2048
                    )
                    if response.content:
                        current_changes = response.content
                except (ValueError, RuntimeError, OSError) as e:
                    logger.warning(f"Rework loop failed: {e}. Continuing with original changes.")
                    break

        if verdict and verdict.final_approved and current_changes != code_changes:
            verdict.reworked_code = current_changes

        return verdict or DebateVerdict(50, False, {}, [], "No debate loops conducted.", [])


# ── Agent Council ──────────────────────────────────────────────────────────

@dataclass
class CouncilMember:
    """An expert persona on the agent council."""
    name: str
    role: str
    system_prompt: str
    vote_weight: float = 1.0


@dataclass
class CouncilVote:
    """Individual vote from a council member."""
    member_name: str
    vote: str  # "approve", "abstain", "reject"
    reasoning: str
    confidence: float  # 0.0–1.0


@dataclass
class CouncilDecision:
    """Final decision produced by the council."""
    topic: str
    votes: list[CouncilVote]
    consensus: str  # "approved", "rejected", "split"
    summary: str
    confidence: float
    majority: float
    duration: float


COUNCIL_MEMBERS: list[CouncilMember] = [
    CouncilMember(
        name="Strategist",
        role="product_strategy",
        system_prompt=(
            "You are a product strategist. Evaluate proposals for market fit, "
            "user value, and strategic alignment. Be concise. Output JSON with "
            "keys: vote ('approve'/'abstain'/'reject'), reasoning, confidence (0-1)."
        ),
        vote_weight=1.2,
    ),
    CouncilMember(
        name="Architect",
        role="technical_architecture",
        system_prompt=(
            "You are a senior software architect. Evaluate proposals for "
            "technical soundness, scalability, and maintainability. Consider "
            "trade-offs and technical debt. Output JSON with keys: vote, reasoning, confidence."
        ),
        vote_weight=1.2,
    ),
    CouncilMember(
        name="Security",
        role="security_audit",
        system_prompt=(
            "You are a security expert. Evaluate proposals for security "
            "implications, threat surface, and compliance. Be paranoid. "
            "Output JSON with keys: vote, reasoning, confidence."
        ),
        vote_weight=1.1,
    ),
    CouncilMember(
        name="Pragmatist",
        role="execution_feasibility",
        system_prompt=(
            "You are a pragmatic engineer focused on execution feasibility. "
            "Evaluate proposals for implementation complexity, timeline, and "
            "resource constraints. Output JSON with keys: vote, reasoning, confidence."
        ),
        vote_weight=1.0,
    ),
    CouncilMember(
        name="UXAdvocate",
        role="user_experience",
        system_prompt=(
            "You are a user experience advocate. Evaluate proposals for "
            "usability, accessibility, and developer experience. Consider "
            "the end-user perspective. Output JSON with keys: vote, reasoning, confidence."
        ),
        vote_weight=0.9,
    ),
]


class Council:
    """Agent Council for strategic decision-making via multi-perspective debate.

    Usage:
        council = Council(provider=llm_provider)
        decision = council.convene(topic="Should we migrate to SQLAlchemy 2.0?",
                                    context="Current ORM is raw SQL...")
    """

    def __init__(
        self,
        provider: LLMProvider | None = None,
        members: list[CouncilMember] | None = None,
        approval_threshold: float = 0.6,
    ):
        self.provider = provider
        self.members = members or COUNCIL_MEMBERS
        self.approval_threshold = approval_threshold

    def convene(
        self,
        topic: str,
        context: str = "",
        include_rebuttals: bool = False,
    ) -> CouncilDecision:
        """Convene the council: collect votes from all members.

        Args:
            topic: The proposal or question to decide on.
            context: Supporting context (background, constraints, options).
            include_rebuttals: If True, run a second round where members
                see each other's votes and can change their position.

        Returns:
            CouncilDecision with consolidated result.
        """
        start = time.time()

        round1_votes = self._collect_votes(topic, context)

        if include_rebuttals and self.provider:
            round2_votes = self._rebuttal_round(topic, context, round1_votes)
            all_votes = round2_votes
        else:
            all_votes = round1_votes

        decision = self._tally(topic, all_votes, time.time() - start)
        return decision

    def _collect_votes(self, topic: str, context: str) -> list[CouncilVote]:
        """Collect independent votes from all council members."""
        votes: list[CouncilVote] = []

        if not self.provider:
            return self._heuristic_votes(topic)

        full_context = f"Topic: {topic}\n\nContext:\n{context}" if context else f"Topic: {topic}"

        with ThreadPoolExecutor(max_workers=len(self.members)) as executor:
            futures = {}
            for member in self.members:
                future = executor.submit(self._ask_member, member, full_context)
                futures[future] = member

            for future in as_completed(futures):
                try:
                    vote = future.result()
                    if vote:
                        votes.append(vote)
                except Exception as e:
                    member = futures[future]
                    logger.warning("Council member '%s' failed: %s", member.name, e)
                    votes.append(CouncilVote(
                        member_name=member.name,
                        vote="abstain",
                        reasoning=f"Error: {e}",
                        confidence=0.0,
                    ))

        return votes

    def _ask_member(self, member: CouncilMember, context: str) -> CouncilVote | None:
        """Ask a single council member for their vote."""
        if not self.provider:
            return None
        try:
            messages = [
                Message(role=Role.SYSTEM, content=member.system_prompt),
                Message(role=Role.USER, content=context),
            ]
            response = self.provider.chat_completion(
                messages=messages,
                temperature=0.2,
                max_tokens=512,
            )
            content = (response.content or "").strip()
            if "```" in content:
                match = re.search(r"```(?:json)?\s*\n?(.*?)\n?```", content, re.DOTALL)
                if match:
                    content = match.group(1).strip()

            start_idx = content.find("{")
            end_idx = content.rfind("}") + 1
            if start_idx >= 0 and end_idx > start_idx:
                data = json.loads(content[start_idx:end_idx])
            else:
                data = json.loads(content)

            vote_str = str(data.get("vote", "abstain")).lower()
            if vote_str not in ("approve", "abstain", "reject"):
                vote_str = "abstain"

            return CouncilVote(
                member_name=member.name,
                vote=vote_str,
                reasoning=str(data.get("reasoning", "")),
                confidence=min(1.0, max(0.0, float(data.get("confidence", 0.5)))),
            )
        except Exception as e:
            logger.debug("Member '%s' vote parse failed: %s", member.name, e)
            return CouncilVote(
                member_name=member.name,
                vote="abstain",
                reasoning=f"Failed to parse response: {e}",
                confidence=0.0,
            )

    def _rebuttal_round(
        self,
        topic: str,
        context: str,
        round1_votes: list[CouncilVote],
    ) -> list[CouncilVote]:
        """Second round where members see each other's votes and may change."""
        if not self.provider or len(round1_votes) < 2:
            return round1_votes

        summary_lines = ["\nRound 1 votes:"]
        for v in round1_votes:
            summary_lines.append(f"- {v.member_name}: {v.vote} (confidence {v.confidence:.1f}) — {v.reasoning[:200]}")
        round1_summary = "\n".join(summary_lines)

        round2_votes: list[CouncilVote] = []
        for member in self.members:
            existing = next((v for v in round1_votes if v.member_name == member.name), None)
            rebuttal_prompt = (
                f"Topic: {topic}\n"
                f"Context: {context}\n\n"
                f"{round1_summary}\n\n"
                f"Your initial vote was: {existing.vote if existing else 'N/A'}\n"
                "After seeing all arguments, do you maintain your position or change it? "
                "Output JSON with keys: vote, reasoning, confidence."
            )
            try:
                messages = [
                    Message(role=Role.SYSTEM, content=member.system_prompt),
                    Message(role=Role.USER, content=rebuttal_prompt),
                ]
                response = self.provider.chat_completion(
                    messages=messages, temperature=0.2, max_tokens=512,
                )
                content = (response.content or "").strip()
                if "```" in content:
                    match = re.search(r"```(?:json)?\s*\n?(.*?)\n?```", content, re.DOTALL)
                    if match:
                        content = match.group(1).strip()
                start_idx = content.find("{")
                end_idx = content.rfind("}") + 1
                if start_idx >= 0 and end_idx > start_idx:
                    data = json.loads(content[start_idx:end_idx])
                else:
                    data = json.loads(content)
                vote_str = str(data.get("vote", "abstain")).lower()
                if vote_str not in ("approve", "abstain", "reject"):
                    vote_str = "abstain"
                round2_votes.append(CouncilVote(
                    member_name=member.name,
                    vote=vote_str,
                    reasoning=str(data.get("reasoning", existing.reasoning if existing else "")),
                    confidence=min(1.0, max(0.0, float(data.get("confidence", existing.confidence if existing else 0.5)))),
                ))
            except Exception as e:
                round2_votes.append(existing or CouncilVote(
                    member_name=member.name, vote="abstain", reasoning=f"Rebuttal failed: {e}", confidence=0.0,
                ))

        return round2_votes

    def _tally(self, topic: str, votes: list[CouncilVote], duration: float) -> CouncilDecision:
        """Tally votes and produce final decision."""
        if not votes:
            return CouncilDecision(
                topic=topic, votes=[], consensus="rejected",
                summary="No votes collected.", confidence=0.0,
                majority=0.0, duration=duration,
            )

        weighted = {"approve": 0.0, "abstain": 0.0, "reject": 0.0}
        total_weight = 0.0

        for v in votes:
            member = next((m for m in self.members if m.name == v.member_name), None)
            w = (member.vote_weight if member else 1.0) * v.confidence
            weighted[v.vote] += w
            total_weight += w

        approve_pct = weighted["approve"] / total_weight if total_weight > 0 else 0.0
        reject_pct = weighted["reject"] / total_weight if total_weight > 0 else 0.0

        if approve_pct >= self.approval_threshold:
            consensus = "approved"
        elif reject_pct >= self.approval_threshold:
            consensus = "rejected"
        else:
            consensus = "split"

        summary_lines = [
            f"Council Decision: {consensus.upper()}",
            f"Approve: {approve_pct:.0%}  |  Reject: {reject_pct:.0%}  |  Abstain: {weighted['abstain'] / total_weight:.0%}" if total_weight > 0 else "",
            "",
        ]
        for v in votes:
            icon = {"approve": "+1", "abstain": "(_)", "reject": "-1"}.get(v.vote, "?")
            summary_lines.append(f"- {icon} {v.member_name}: {v.reasoning[:120]}")

        return CouncilDecision(
            topic=topic,
            votes=votes,
            consensus=consensus,
            summary="\n".join(summary_lines),
            confidence=approve_pct if consensus == "approved" else (1.0 - reject_pct),
            majority=approve_pct,
            duration=duration,
        )

    def _heuristic_votes(self, topic: str) -> list[CouncilVote]:
        """Fallback rule-based voting when no LLM is available."""
        t = topic.lower()
        votes: list[CouncilVote] = []

        for member in self.members:
            if member.role == "product_strategy" and ("migrate" in t or "refactor" in t):
                votes.append(CouncilVote(member.name, "approve", "Strategic value in modernization.", 0.6))
            elif member.role == "security_audit" and ("migrate" in t or "upgrade" in t):
                votes.append(CouncilVote(member.name, "approve", "Newer versions have fewer vulnerabilities.", 0.7))
            elif member.role == "execution_feasibility" and ("large" in t or "complex" in t):
                votes.append(CouncilVote(member.name, "abstain", "Need more implementation detail.", 0.4))
            else:
                votes.append(CouncilVote(member.name, "approve", "Heuristic: default approve.", 0.5))

        return votes
